### ISSUE TITLE
Cowsay breaks Ctrl-C shortcut on Linux

### ISSUE THREAD

**Issue by dappiu** [rafadc/cowsay#1]
When Cowsay package is enabled, CTRL+c shortcut to copy selection get a strange behaviour. Sometimes, it copies a white line, sometimes it copies the line that precedes the line in which selection is (but it never copies what you selected).

I just built atom v0.165.0 on Linux w510 3.16.5-gentoo #1 SMP PREEMPT Fri Dec 12 11:23:22 CET 2014 x86_64 Intel(R) Core(TM) i7 CPU Q 820 @ 1.73GHz GenuineIntel GNU/Linux.
But the issue is present since I installed Cowsay several days ago, when I had Atom version 0.135.0.

If I can do something to investigate the issue, tell me, I'll be happy to help!

**Comment by rafadc** [comment]
I just tested it on OSX. I'm preparing a Virtual machine right now to be able to reproduce. Probably it has something to do with CRTL-c not being used for copying in Mac ;)

Thanks for reporting it!

**Comment by rafadc** [comment]
I've been trying but I've not been able to reproduce.

Can you open the keybinding inspector (CTRL-.) and check what keybinding is affecting your copy?

Thanks a lot.

**Comment by dappiu** [comment]
I'll try to explain in details the behaviour I'm experiencing:

ctrl-c is the default keybinding on Linux and Windows to copy selected text
on buffer.

Cowsay per default binds itself with "ctrl-c ctrl-s" keybinding (to make it
work I have to keep CTRL key pressed while pressing C key followed by S key)

Searching string "ctrl-c" on search bar of Keybindings panel of Atom
editor, I get the following bindings:

'body':
  'ctrl-c': 'core:copy'

'body .native-key-bindings':
  'ctrl-c': 'native!'

'.cli-status':
  'ctrl-c': 'native!'

'.platform-win32 .tree-view, .platform-linux .tree-view':
  'ctrl-c': 'tree-view:copy'

'.editor':
  'ctrl-c ctrl-s': 'cowsay:cowsay'

Now, with Cowsay enabled, If I select some text and press CTRL-c the
selection don't get copied (the buffer contains what was there before, or
nothing, if there was nothing).
Pressing repeatedly, sometimes, something get copied, but what ends in the
buffer is not what I selected.
As I said previously, most of the times what ends in the copy buffer is the
line above the line that I selected but even stranger things can happen
(sometimes even "backspaces" are copied, so when I paste some text gets
deleted), and I can't find a meaning of this behaviour.

Obviously, disabling Cowsay the normal behaviour is restored. I would
change the default keybinding of Cowsay, can you tell me how I can do this?

Many thanks,
DR

2015-01-05 0:16 GMT+01:00 Rafa de Castro notifications@github.com:

> I've been trying but I've not been able to reproduce.
> 
> Can you open the keybinding inspector (CTRL-.) and check what keybinding
> is affecting your copy?
> 
> Thanks a lot.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rafadc/cowsay/issues/1#issuecomment-68654253.

## 

Davide Rossi

GnuPG/PGP Key ID: 4AE92D78
FINGERPRINT: 33A1 9E37 C91A DDC7 0231 FDE1 AB8D 2D4A 4AE9 2D78
Server: pgp.mit.edu

**Comment by rafadc** [comment]
To be honest I was never able to reproduce. I changed anyway the default shortcut to CTRL-L in the last version.

You can anyway remap your keybindings in your keybindings file with:

```
'atom-text-editor':
  'ctrl-l': 'cowsay:cowsay'
```
